In [1]:
using CSV
using DataFrames
using SparseArrays
using LinearAlgebra


┌ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
└ @ Base loading.jl:1278
┌ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
└ @ Base loading.jl:1278


In [2]:
include("setup_analysis.jl")
include("support_functions.jl")

sort_row_ids (generic function with 1 method)

In [3]:
mc = read_csv("/Users/jsyme/Desktop/testmc.csv", true);
cats = names(mc);
Q = coalesce.(Matrix(mc), 0)

In [28]:
ee = eigen(Q)

Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}
values:
6-element Array{Complex{Float64},1}:
 0.9687602078756405 + 0.0im
 0.9841107631803048 - 0.0049710291040192004im
 0.9841107631803048 + 0.0049710291040192004im
 0.9880182657637496 + 0.0im
 0.9899999999999999 + 0.0im
 0.9999999999999993 + 0.0im
vectors:
6×6 Array{Complex{Float64},2}:
   -0.923815+0.0im  0.0604625-0.163615im   …  -0.136083+0.0im  0.408248+0.0im
 -0.00781669+0.0im   0.153643-0.406988im       0.136083+0.0im  0.408248+0.0im
   -0.108855+0.0im  -0.322349-0.0344988im      0.136083+0.0im  0.408248+0.0im
    0.320351+0.0im   0.608628-0.0im            0.136083+0.0im  0.408248+0.0im
   -0.108855+0.0im  -0.322349-0.0344988im     -0.952579+0.0im  0.408248+0.0im
     0.14206+0.0im  -0.263249+0.361115im   …  -0.136083+0.0im  0.408248+0.0im

In [49]:
lambdas = collect(ee.values)
aa = ee.vectors[:, 1]

6-element Array{Complex{Float64},1}:
  -0.9238151400401169 + 0.0im
 -0.00781669134199983 + 0.0im
 -0.10885482888543022 + 0.0im
   0.3203509787255466 + 0.0im
 -0.10885482888543216 + 0.0im
  0.14205980872630536 + 0.0im

In [69]:
(diagm(ones(size(Q)[2])) - Q)*ee.vectors[:, 6]

6-element Array{Complex{Float64},1}:
 -1.5048726154098802e-16 + 0.0im
  1.0755285551056204e-16 + 0.0im
  1.8301332671555315e-16 + 0.0im
  -3.235259282696745e-16 + 0.0im
     4.9439619065339e-17 + 0.0im
    7.19910242530375e-17 + 0.0im

In [51]:
lambdas[1]*aa

6-element Array{Complex{Float64},1}:
   -0.8949553471039277 + 0.0im
 -0.007572499529375475 + 0.0im
  -0.10545422665931665 + 0.0im
    0.3103432807433254 + 0.0im
  -0.10545422665931854 + 0.0im
    0.1376218898324693 + 0.0im

In [58]:
ee.vectors

6×6 Array{Complex{Float64},2}:
   -0.923815+0.0im  0.0604625-0.163615im   …  -0.136083+0.0im  0.408248+0.0im
 -0.00781669+0.0im   0.153643-0.406988im       0.136083+0.0im  0.408248+0.0im
   -0.108855+0.0im  -0.322349-0.0344988im      0.136083+0.0im  0.408248+0.0im
    0.320351+0.0im   0.608628-0.0im            0.136083+0.0im  0.408248+0.0im
   -0.108855+0.0im  -0.322349-0.0344988im     -0.952579+0.0im  0.408248+0.0im
     0.14206+0.0im  -0.263249+0.361115im   …  -0.136083+0.0im  0.408248+0.0im

In [56]:
Q

6×6 Array{Real,2}:
 0.97   0.01   0.005  0.005  0.005  0.005
 0      0.99   0.005  0      0      0.005
 0      0      0.99   0.005  0      0.005
 0.005  0.005  0.005  0.985  0      0
 0      0      0      0.005  0.99   0.005
 0.005  0      0      0.005  0      0.99